cloud:
  aws:
    credentials:
      access-key: AKIATO7MDQR6VN6EPP7A
      secret-key: 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
    region:
      static: eu-west-2
      stack:
        auto: false
application:
  bucket:
    name: test-s3-upload2023